server:
  port: 8001

spring:
  # mysql\u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_quartz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.wyp.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true